### **<center>NumPy</center>**

##### NumPy is a Python library used for numerical computing. It provides a powerful data structure called arrays (specifically, ndarray), which is more efficient than Python lists for handling large datasets and performing mathematical operations.

##### **Uses of NumPy**

##### **Fast Performance** – NumPy arrays are faster than Python lists because they store data in contiguous memory blocks and use optimized C-based operations.
##### **Efficient Memory Usage** – NumPy arrays use less memory compared to lists, making them suitable for large datasets.
##### **Mathematical and Statistical Functions** – Provides built-in functions for operations like mean, median, standard deviation, etc.
##### **Vectorized Operations** – NumPy allows element-wise operations without explicit loops, improving speed and efficiency.
##### **Integration with Other Libraries** – Libraries like Pandas, SciPy, TensorFlow, and Scikit-learn rely on NumPy for numerical computations.

##### **Creating a NumPy Array**

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
type(arr)
len(arr)
arr.ndim
arr.shape
arr.reshape(5, -2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
#Initalized the numpy array from nested python list
mylist1 = [1, 2, 3, 4, 5, 6]
mylist2 = [2, 3, 4, 5, 6, 8]
mylist3 = [9, 6, 5, 7, 4, 3]
mul_arr = np.array([mylist1, mylist2, mylist3])
print(mul_arr)

[[1 2 3 4 5 6]
 [2 3 4 5 6 8]
 [9 6 5 7 4 3]]


In [21]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Creating a NumPy array with zeros
zeros_arr = np.zeros((3, 3))
print(zeros_arr)

# Creating a NumPy array with ones
ones_arr = np.ones((2, 2))
print(ones_arr)

# Creating an array with random numbers
random_arr = np.random.rand(3, 3)
print(random_arr)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.34049575 0.30326619 0.75110544]
 [0.25644731 0.55921679 0.04926878]
 [0.65739374 0.71270716 0.30522007]]


##### Range

In [30]:
r = range(25)
print(r)

range(0, 25)


In [43]:
r = np.arange(48)
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [44]:
rr = r.reshape(6, 4, 2)
print(rr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]

 [[32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]]]


##### **NumPy Array Attributes**

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # (Rows, Columns)
print("Size:", arr.size)    # Total elements
print("Data Type:", arr.dtype)  # Type of elements
print("Dimensions:", arr.ndim)  # Number of dimensions
print("Item Size:", arr.itemsize)  # Size of each element in bytes
print("Total Bytes:", arr.nbytes)  # Total memory consumed


Shape: (2, 3)
Size: 6
Data Type: int32
Dimensions: 2
Item Size: 4
Total Bytes: 24


##### **NumPy Numeric Operations**

In [72]:
mylist1 = np.array([[1, 2, 3],[ 4, 5, 6]])
mylist2 = np.array([[2, 3, 4],[ 5, 6, 8]])
print(mylist1)
print(mylist2)
mylist1.shape
mylist2.shape

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 8]]


(2, 3)

##### **Addition**

In [55]:
print(mylist1+mylist2)

[[ 3  5  7]
 [ 9 11 14]]


In [60]:
print(np.add(mylist1, mylist2))

[[ 3  5  7]
 [ 9 11 14]]


##### **Substraction**

In [61]:
print(mylist1 - mylist2)

[[-1 -1 -1]
 [-1 -1 -2]]


In [64]:
print(np.subtract(mylist1, mylist2))

[[-1 -1 -1]
 [-1 -1 -2]]


##### **Multiplication**

In [65]:
print(mylist1 * mylist2)

[[ 2  6 12]
 [20 30 48]]


In [67]:
print(np.multiply(mylist1, mylist2))

[[ 2  6 12]
 [20 30 48]]


##### **Matrix Multiplication Rules**

##### 1️⃣ Matrix multiplication (np.dot(A, B)) requires inner dimensions to match:

##### Example: (2,3) × (3,2) = ✅ (2,2)
##### Example: (2,3) × (2,3) = ❌ Not Possible
##### 2️⃣ Fixes for (2,3) × (2,3) issue:

##### Transpose one matrix → np.dot(A, B.T) ✅
##### Reshape B to (3,2) → np.dot(A, B) ✅
##### Use * for element-wise multiplication (not matrix multiplication) ✅

In [74]:
print(np.dot(mylist1, mylist2.T))

[[20 41]
 [47 98]]


##### **Division**

In [75]:
(mylist1 / mylist2)

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.75      ]])

In [76]:
np.divide(mylist1, mylist2)

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.75      ]])

#### **Summation**

###### **add overall element**

In [79]:
np.sum(mylist1) #
np.sum(mylist2)

28

In [80]:
np.sum(mylist1, axis = 0) # add element of Each Column

array([5, 7, 9])

In [81]:
np.sum(mylist1, axis = 1) # Add eclment of Each Row

array([ 6, 15])